// Regenerates src/rules.ts from the latest ruff release.
// Usage: node scripts/generate-rules.mjs
// Requires uv (https://docs.astral.sh/uv/) so the latest ruff can be run via uvx.
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const raw = execFileSync('uvx', ['ruff', 'rule', '--all', '--output-format', 'json'], {
  encoding: 'utf8',
  maxBuffer: 64 * 1024 * 1024,
  shell: process.platform === 'win32',
})
const ruffVersion = execFileSync('uvx', ['ruff', '--version'], {
  encoding: 'utf8',
  shell: process.platform === 'win32',
}).trim().split(/\s+/)[1]

const allRules = JSON.parse(raw)

const rules = allRules.map(rule => ({
  name: rule.name,
  code: rule.code,
  linter: rule.linter,
  summary: rule.summary,
  message_formats: rule.message_formats,
  fix: rule.fix,
  explanation: rule.explanation,
  preview: rule.preview,
}))

const header = `// Auto-generated by scripts/generate-rules.mjs from ruff ${ruffVersion} — do not edit manually.

export interface RuffRule {
  name: string
  code: string
  linter: string
  summary: string
  message_formats: string[]
  fix: string
  explanation: string
  preview: boolean
}

export const rules: RuffRule[] = `

const footer = `

export const prefixToLinterMap = rules.reduce((map, rule) => {
  const match = rule.code.match(/^[A-Z]+/)
  if (match) {
    const prefix = match[0]
    if (!map.has(prefix)) {
      map.set(prefix, rule.linter)
    }
  }
  return map
}, new Map<string, string>())
`

writeFileSync(join(root, 'src', 'rules.ts'), header + JSON.stringify(rules, null, 2) + footer)

console.log(`Generated src/rules.ts: ${rules.length} rules from ruff ${ruffVersion}`)
